### ISSUE TITLE
MyPageOrder & MyPageViewed 관련

### ISSUE THREAD

**Issue by sukchanlee1** [wafflestudio20-5/team4-web#20]
#19 PR에서 main과의 conflict를 해결하는 과정에서 MyPageOrder & MyPageViewed의 코드 중 일부분을 주석 처리 해놓은 것이 있습니다.
GET api/user/me로 가져오는 User 정보에 purchases와 recentlyViewed 필드가 없기 때문인데요.
사실 제가 유저 정보 가져올 때 구매 내역, 최근 본 상품, 남긴 후기 등을 한꺼번에 가져오기로 했는지, 아니면 별도의 api를 구축하기로 했는지 명확히 기억이 나지 않습니다...

만약에 별도의 api를 통해서 해당 정보들을 가져온다면 Purchase[]나 Item[]을 반환하는 api 호출 훅을 api.ts에 짜면 될 것 같고,
한번에 가져오게 된다면 User interface를 extend하는 인터페이스를 새로 정의한 뒤, 그러한 GET api/user/me를 감싸는 api 호출 훅이 그러한 인터페이스를 반환하도록 코드를 리팩토링하시면 될 것 같습니다.

`interface UserInfo {
    user: User,
    reviews: Review[],
    purchases: Purchase[],
    shoppingCart: Item[],
    recentlyViewed: Item[],
    itemInquiry: Inquiry[],
    personalInquiry: Inquiry[],
`

그런데 써놓고 보니 상당히 정보가 많아서 별도의 api로 찢는 것도 괜찮을 것 같습니다. 아직 안 정해진 사안이라면 오늘 회의 때 이야기해보면 되겠네요.
PR 머지하는 과정에서 예상치 못한 불편을 끼쳐드려 죄송합니다... 🙏

**Comment by hitkoo** [comment]
아닙니다 api연동 편하게하는거 큰작업이었는데 뚝딱해주셔서 되려 너무 감사합니다. 둘다 제가 작업한 페이지이니 오늘 회의때 model 협의잘보고 주석처리해두신거 잘 해결해놓겠습니다
