### ISSUE TITLE
GET api/items 호출 시 무한 로딩 문제

### ISSUE THREAD

**Issue by sukchanlee1** [wafflestudio20-5/team4-web#22]

**Comment by hitkoo** [comment]
![image](https://user-images.githubusercontent.com/107466434/211671969-21e15ba6-0c2e-4763-8851-f2708bffee38.png)

즉, api 요청이 처리되기전에 또 api콜을 해서 인거 같습니다. 제가 로컬 설정 & 백엔드 공부를 하다가 밤을 새버려서 자고 일어나서 해결해보겠습니다.

+ 기존 코드 &  json server에 console.log로 확인해보니 빈 object 5~6번 찍은 뒤 item data가 제대로 찍히는거로 봐서 loading component 구현 or useeffect로 해결해야 할 것 같다는 생각이 드는데 더 좋은 해결방안 아는거 있으신가요??

**Comment by hitkoo** [comment]
지금 거의 네시간 붙들었는데 도저히 해결이 안되네요.....

이 이슈 빨리 해결하는게 좋을 것 같은데 오늘 잠깐 얘기가능할까요?? 글로 남기기에는 머리에 추상적으로 문제가 보이고 정리가 안돼서

**Comment by TheoLee72** [comment]
` 
 useEffect(() => {
    if (!fetch) return;
    const source = axios.CancelToken.source();
    setResult((prev) => ({ ...prev, loading: true }));
    fetch(source.token)
      .then((res) => {
        setResult({ data: res.data, loading: false });
      })
      .catch((err) => {
        if (axios.isCancel(err)) return;
        setResult({ error: { payload: err }, loading: false });
      });
    return () => source.cancel();
  }, [fetch]);
  return { data, loading, error };
}
`
여기에서 계속 돌아서 그런거 같은데 맞나요?

**Comment by hitkoo** [comment]
그런 것 같습니다
