### ISSUE TITLE
상세 페이지 남은 이슈들 정리

### ISSUE THREAD

**Issue by sukchanlee1** [wafflestudio20-5/team4-web#33]
- [x] 선택한 옵션을 삭제하면 드롭다운의 텍스트도 '옵션 선택'으로 바뀌게끔 구현
- [x] 장바구니에 상품을 넣은 이후 '장바구니로 이동하시겠습니까?' 모달 구현
- [x] 장바구니 모달 애니메이션 구현
- [x] 409 에러의 경우 '이미 장바구니에 있는 상품입니다' 토스트 메시지 띄우기
- [x] 사진 배열 배치 마우스에 따라 이상해지는 문제 해결 ([관련 코멘트](https://github.com/wafflestudio20-5/team4-web/issues/33#issuecomment-1396470052))
- [x] 세일하지 않는 상품의 경우 가격 정보에 oldPrice를 정상적으로 띄우기 ([관련 코멘트](https://github.com/wafflestudio20-5/team4-web/issues/33#issuecomment-1396470052))
---
- [x] 구매후기 영역 레이아웃 잡기
- [x] 구매후기 영역 로직(페이지네이션, 댓글 작성 등) 구현
- [x] 구매후기 영역 api 연결
- [x] 상품문의 영역 레이아웃 잡기
- [x] 상품문의 영역 로직(페이지네이션 등) 구현
- [x] 상품문의 영역 api 연결
- [ ] 상세 페이지 최하단에 Footer 붙이기

**Comment by hitkoo** [comment]
409(장바구니에 이미 있는 Item 또 넣을 때)에러 시 toast 처리도 하면 좋을 것 같습니다

**Comment by sukchanlee1** [comment]
> 409(장바구니에 이미 있는 Item 또 넣을 때)에러 시 toast 처리도 하면 좋을 것 같습니다

앗 이미 처리를 한 것... 같은데 혹시 제가 말씀하신 내용을 잘못 이해한 걸까요?

**Comment by hitkoo** [comment]
> > 409(장바구니에 이미 있는 Item 또 넣을 때)에러 시 toast 처리도 하면 좋을 것 같습니다
> 
> 앗 이미 처리를 한 것... 같은데 혹시 제가 말씀하신 내용을 잘못 이해한 걸까요?
 ```
     } catch (error) {
        const e = error as AxiosError;
        if (e.response?.status === 409) {
          toast('이미 장바구니에 있는 상품입니다.');
        }
```


어.. 코드 보니까 있네요... 근데 제 로컬에서는 작동을 안하는 것 같아요. 혹시 석찬님 로컬에서는 작동하나요??

**Comment by Boseong-Seo** [comment]
그리고 상세 페이지의 
조그마한 상품 상세 사진에서 마우스가 어딨는지에 따라 배열이 조금씩 달라지더라고요.
그래서 이 부분에 대한 수정도 필요할 것 같습니다 !

![image](https://user-images.githubusercontent.com/90292371/213345619-75127f1a-18ff-4c54-998e-13b6489cbf4c.png)
![image (1)](https://user-images.githubusercontent.com/90292371/213345613-a5f83104-3fda-4c5a-8dcd-ad259079078f.png)

**Comment by Boseong-Seo** [comment]
상세 페이지의 조그마한 상품 상세 사진들에서 마우스가 어디에 있는지에 따라 배열이 조금씩 달라집니다.
이에 대한 수정이 필요해보여 말씀드립니다 !
(아래 캡처 사진은 어제자이긴 한데, 좀전에 확인했을 때에도 동일하게 관측되고 있습니다.)

![image](https://user-images.githubusercontent.com/90292371/213365293-7fc4685b-4d26-40d9-bf2f-98b125d3eb20.png)
![image (1)](https://user-images.githubusercontent.com/90292371/213365286-c82d4326-8714-429b-a79a-0390dd3402a5.png)

**Comment by Boseong-Seo** [comment]
그리고, 세일하지 않는 상품의 경우, Item의 newPrice와 sale 필드가 null로 되어 있는데,
그래서인지 가격이 원가에 취소선만 그어져있는 형태로만 제시되어 있더라고요.
이에 대한 수정도 필요할 것 같습니다 .. !
![image](https://user-images.githubusercontent.com/90292371/213365602-6268c696-47ca-4241-9d5d-5e0c59ec32b4.png)

**Comment by Boseong-Seo** [comment]
@sukchan-0811 덧붙여, 상품 문의 영역 관련하여, 상품 문의 작성도 석찬님이 담당해주시는 게 맞을까요 ?!
상품 문의 작성이 상품 상세 페이지에서만 가능해서,
처음에는 (개인페이지에서 상품 문의 작성이 가능하다고 착각해서) POST  `/api/user/me/item-inquiries` 로 노션 api 문서에 작성해뒀는데, 위 형태가 아닌 POST `/api/item/:id/inquiry` 로 수정해야 할 것 같아 여쭤봅니다 !

**Comment by sukchanlee1** [comment]
@Boseong-Seo 
네 제가 담당하면 될 것 같습니다. POST `/api/item/:id/inquiry`로 수정하는 것도 좋을 것 같네요.
노션에 API 명세를 적어두었는데 한번 확인해보시고 이상 없으면 Item API 목록으로 옮겨주시면 감사하겠습니다.
