### ISSUE TITLE
메인 페이지, 아이템 리스트 페이지 레이아웃

### ISSUE THREAD

**Issue by sukchanlee1** [wafflestudio20-5/team4-web#49]
### 1. 메인 페이지: 가운데 맞춤 안 됨
<img width="2425" alt="Screenshot 2023-01-25 at 12 30 40 AM" src="https://user-images.githubusercontent.com/100818542/214336796-7df3e7f2-d829-4d9b-af94-ee374337eb5a.png">

### 2. 아이템 리스트 페이지: 보여줄 아이템 항목이 하나인 경우 화면 전체를 차지하는 문제
<img width="2425" alt="Screenshot 2023-01-25 at 12 30 47 AM" src="https://user-images.githubusercontent.com/100818542/214336761-708b0d82-697c-4682-9817-cc462f5d88a0.png">

**Comment by hitkoo** [comment]
해결했습니다
