### ISSUE TITLE
ItemListPage Label, rating

### ISSUE THREAD

**Issue by hitkoo** [wafflestudio20-5/team4-web#51]
- [ ] ItemListPage Label, rating  //

**Comment by sukchanlee1** [comment]
맨 밑 이슈 두 개는 제가 구현하겠습니다!

**Comment by sukchanlee1** [comment]
혹시 여기 있는 이슈들은 어떤 브랜치에서 작업 중이신가요?

**Comment by hitkoo** [comment]
HomePage 관련된 1개 이슈제외 아직 안건드렸습니다! HomePage Style탭 마무리중입니다

**Comment by sukchanlee1** [comment]
엇 검색시 정렬 탭 없애기는 아직 안 하신건가요 그럼?

**Comment by hitkoo** [comment]
네 그거 그냥 렌더안되게 했더니 뭔가 위에 동강날라가는 느낌이어서 어떻게 할지 고민 중이었습니다
