### ISSUE TITLE
실제로 로그인 안되어있을때 refresh 400

### ISSUE THREAD

**Issue by hitkoo** [wafflestudio20-5/team4-web#65]
실제로 로그인 안되어있을때는 refresh 안가게 하면 좋을 것 같습니다. 가능할까요

**Comment by sukchanlee1** [comment]
어떤 이슈인지 조금만 더 자세히 설명해주실 수 있나요?

**Comment by hitkoo** [comment]
![image](https://user-images.githubusercontent.com/107466434/216398270-e745ec67-d225-47e5-ae78-d5f4ac87638d.png)
실제로 비로그인상태일때 콘솔에 400에러 찍히는 현상 말한겁니다. 상관없을까요?
